package modelo;
// Generated 29-may-2019 12:52:29 by Hibernate Tools 4.3.1



/**
 * Emulador generated by hbm2java
 */
public class Emulador  implements java.io.Serializable {


     private int idemulador;
     private String nombre;
     private String ver;
     private String consola;

    public Emulador() {
    }

    public Emulador(int idemulador, String nombre, String ver, String consola) {
       this.idemulador = idemulador;
       this.nombre = nombre;
       this.ver = ver;
       this.consola = consola;
    }
   
    public int getIdemulador() {
        return this.idemulador;
    }
    
    public void setIdemulador(int idemulador) {
        this.idemulador = idemulador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getVer() {
        return this.ver;
    }
    
    public void setVer(String ver) {
        this.ver = ver;
    }
    public String getConsola() {
        return this.consola;
    }
    
    public void setConsola(String consola) {
        this.consola = consola;
    }




}


