package modelo;
// Generated 29-may-2019 12:52:29 by Hibernate Tools 4.3.1



/**
 * Juego generated by hbm2java
 */
public class Juego  implements java.io.Serializable {


     private int idjuego;
     private String titulo;
     private String consola;
     private String genero;
     private String njugadores;

    public Juego() {
    }

	
    public Juego(int idjuego) {
        this.idjuego = idjuego;
    }
    
    public Juego(int idjuego, String titulo, String consola, String genero, String njugadores) {
       this.idjuego = idjuego;
       this.titulo = titulo;
       this.consola = consola;
       this.genero = genero;
       this.njugadores = njugadores;
    }
   
    public int getIdjuego() {
        return this.idjuego;
    }
    
    public void setIdjuego(int idjuego) {
        this.idjuego = idjuego;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getConsola() {
        return this.consola;
    }
    
    public void setConsola(String consola) {
        this.consola = consola;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getNjugadores() {
        return this.njugadores;
    }
    
    public void setNjugadores(String njugadores) {
        this.njugadores = njugadores;
    }




}


