package modelo;
// Generated 29-may-2019 12:52:29 by Hibernate Tools 4.3.1



/**
 * Plataforma generated by hbm2java
 */
public class Plataforma  implements java.io.Serializable {


     private int idconsola;
     private String consola;
     private Integer bytes;
     private Integer lanzamiento;
     private String rutaimagen;

    public Plataforma() {
    }

	
    public Plataforma(int idconsola) {
        this.idconsola = idconsola;
    }
    public Plataforma(int idconsola, String consola, Integer bytes, Integer lanzamiento, String rutaimagen) {
       this.idconsola = idconsola;
       this.consola = consola;
       this.bytes = bytes;
       this.lanzamiento = lanzamiento;
       this.rutaimagen = rutaimagen;
    }
   
    public int getIdconsola() {
        return this.idconsola;
    }
    
    public void setIdconsola(int idconsola) {
        this.idconsola = idconsola;
    }
    public String getConsola() {
        return this.consola;
    }
    
    public void setConsola(String consola) {
        this.consola = consola;
    }
    public Integer getBytes() {
        return this.bytes;
    }
    
    public void setBytes(Integer bytes) {
        this.bytes = bytes;
    }
    public Integer getLanzamiento() {
        return this.lanzamiento;
    }
    
    public void setLanzamiento(Integer lanzamiento) {
        this.lanzamiento = lanzamiento;
    }
    public String getRutaimagen() {
        return this.rutaimagen;
    }
    
    public void setRutaimagen(String rutaimagen) {
        this.rutaimagen = rutaimagen;
    }




}


